version: '3'

services:
  simplemanager:
    build: .
    image: simplemanager
    ports:
      - 9000
    links:
      - mysql
      - redis
#    networks:
#      - backend
    volumes:
      - sources:/opt
      - var:/opt/simplemanager/var
      - etc:/opt/simplemanager/etc
    tmpfs:
      - /tmp
      - /var/log

  redis:
    image: 'redis:alpine'
    ports:
      - '6379'
#    networks:
#      - backend
#    ports:
#      - '6379:6379'
#    command: php artisan queue:work
#    links:
#      - mysql
#    volumes:
#      - ./:/application

  mysql:
    image: 'mysql:5.7'
    ports:
      - 3306
#    networks:
#      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=laravel-blog
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: 'nginx'
    ports:
      - '8080:80'
#    networks: 
#      - frontend
#      - backend
    volumes:
      - ./files/nginx.conf:/etc/nginx/conf.d/default.conf
      - sources:/opt
    links:
      - simplemanager

volumes:
  var:
  etc:
  db:
  sources:

#networks: 
#  frontend:
#  backend:

