version: '2'

services:
  simplemanager:
    build: .
    image: simplemanager
    ports:
      - 9000
    links:
      - mysql
      - redis
    environment:
      - ADMIN_EMAIL
      - MYSQL_ROOT_PASSWORD
    volumes:
      - sources:/opt
      - var:/opt/simplemanager/var
      - etc:/opt/simplemanager/etc
    tmpfs:
      - /tmp
      - /var/log

  redis:
    image: 'redis:alpine'
    ports:
      - 6379

  mysql:
    image: 'mysql:5.7'
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: 'nginx'
    ports:
      - '8080:80'
    volumes:
      - ./files/nginx.conf:/etc/nginx/conf.d/default.conf
      - sources:/opt
    links:
      - simplemanager

volumes:
  var:
  etc:
  db:
  sources:

